apiVersion: v1
kind: Secret
metadata:
  name: stamina-secrets
  namespace: stamina
type: Opaque
stringData:
  # MongoDB Connection
  MONGODB_URI: "mongodb+srv://harry:harry8atlas@cluster0-tj0q8.mongodb.net/stamina?retryWrites=true&w=majority"

  # JWT Configuration
  JWT_SECRET: "4YdOfiPtyv1aYAjSdr7MidPOnmZHtT4AdLAvQldpHvD2SROwEXS7E1JQHhUn0XEy0bOCCHnI8zIxWKocI7ASb7Kh3uQ0spn9FsZ"
  JWT_EXPIRATION: "1d"

  # RabbitMQ Connection
  RABBITMQ_URI: "amqp://rabbitmq:5672"
